In [1]:
import json
import urllib.request
import pandas as pd

In [2]:
def get_search_url(start_date, end_date, pages, limit):
    base = 'https://open.jejudatahub.net/api/proxy/5D5a577taba7tbb71at1b1bt9tatata9/'
    start = start_date
    end = end_date
    client_key = 'b411t4bjr488rot1bp33t4_428teo32j'
    
    param_date = "?startDate=" + start_date + "&endDate=" + end_date 
    request_param = "&number=" + pages + "&limit=" + limit
    
    return base + client_key + param_date + request_param

In [3]:
def get_result(url):
    request = urllib.request.Request(url)
    response = urllib.request.urlopen(request)
    
    return json.loads(response.read().decode('utf-8'))

In [4]:
def get_fields(json_data):
    sido = [each['sido'] for each in json_data['data']]
    sigungu = [each['sigungu'] for each in json_data['data']]
    cityGubun = [each['cityGubun'] for each in json_data['data']]
    marketType = [each['marketType'] for each in json_data['data']]
    userType = [each['userType'] for each in json_data['data']]
    ageGroup = [each['ageGroup'] for each in json_data['data']]
    gender = [each['gender'] for each in json_data['data']]
    dtYearMonth = [each['dtYearMonth'] for each in json_data['data']]
    userCount = [each['userCount'] for each in json_data['data']]
    useCount = [each['useCount'] for each in json_data['data']]
    useCost = [each['useCost'] for each in json_data['data']]
    
    data_pd = pd.DataFrame({'sido':sido,'sigungu':sigungu,'marketType':marketType,'userType':userType,'gender':gender,'userCount':userCount,'useCount':useCount,'useCost':useCost},
                          columns = ['sido','sigungu','marketType','userType','gender','userCount','useCount','useCost'])
    
    return data_pd

In [5]:
def add_col_row():
    pd.set_option('display.max_row', 500)
    pd.set_option('display.max_columns', 100)
    
add_col_row()

In [6]:
res_jeju_data = pd.DataFrame()

page_count = 1
limit = 100
start_date = '20170101'
end_date = '20181231'

while True:
    
    url = get_search_url(start_date, end_date, str(page_count), str(limit))
    json_data = get_result(url)
    pd_result = get_fields(json_data)
    page_count += 1
    
    if json_data['hasMore'] == False:
        break
        
    res_jeju_data = res_jeju_data.append(pd_result)

In [7]:
# len(res_jeju_data)
res_jeju_data

   sido sigungu marketType userType gender  userCount  useCount   useCost
0   제주도     제주시         유흥     제주도민      여         23        29   4240100
1   제주도     제주시         유흥     제주도민      남        114       190  27414000
2   제주도     제주시         유흥     제주도민      여         52        71   6848000
3   제주도     제주시         유흥     제주도민      남        259       458  91468500
4   제주도     제주시         유흥     제주도민      여         77        99  10021600
..  ...     ...        ...      ...    ...        ...       ...       ...
95  제주도    서귀포시         숙박     제주도민      남         84       102   3846958
96  제주도    서귀포시        식음료   내국인관광객      남         95       163   2656250
97  제주도     제주시         소매     제주도민      남        806      1125  74823494
98  제주도     제주시      문화/레져   내국인관광객      여        877       971  16823000
99  제주도     제주시         숙박   내국인관광객      남        194       276  28666770

[16700 rows x 8 columns]

In [9]:
res_jeju_data.to_csv("jeju_api_res_datas.csv", encoding='utf-8-sig', header=False)